{::
{ ; V1toV2: Added opening brace for [{]
global ; V1toV2: Made function global
MsgBox("open-brace hotkey now supported")
return
} ; V1toV2: Added closing brace for [{]

}::
{ ; V1toV2: Added opening brace for [}]
global ; V1toV2: Made function global
MsgBox("close-brace hotkey now supported")
return
} ; V1toV2: Added closing brace for [}]

[::
{ ; V1toV2: Added opening brace for [[]
global ; V1toV2: Made function global
MsgBox("open-bracket hotkey now supported")
return
} ; V1toV2: Added closing brace for [[]

:::
{ ; V1toV2: Added opening brace for [:]
global ; V1toV2: Made function global
MsgBox("colon hotkey now supported")
return
} ; V1toV2: Added closing brace for [:]

`;::
{ ; V1toV2: Added opening brace for [`;]
global ; V1toV2: Made function global
MsgBox("semi-colon hotkey now supported")
return
} ; V1toV2: Added closing brace for [`;]