{::
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
MsgBox("open-brace hotkey now supported")
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

}::
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
MsgBox("close-brace hotkey now supported")
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

[::
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
MsgBox("open-bracket hotkey now supported")
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

:::
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
MsgBox("colon hotkey now supported")
return
} ; V1toV2: Added Bracket before hotkey or Hotstring

`;::
{ ; V1toV2: Added bracket
global ; V1toV2: Made function global
MsgBox("semi-colon hotkey now supported")
return
} ; V1toV2: Added bracket in the end