myGui := Gui()
myVar := myGui.Hwnd
myGui.Opt("+AlwaysOnTop -Caption +Owner +LastFound"), myVar := myGui.Hwnd
myGui.Opt("+AlwaysOnTop -Caption +Owner +LastFound"), myVar := myGui.Hwnd
myGui.Opt("+AlwaysOnTop -Caption +Owner +LastFound"), myVar := myGui.Hwnd

var1 := myGui.Hwnd, var2 := myGui.Hwnd
myGui.Opt("-Caption"), var1 := myGui.Hwnd, var2 := myGui.Hwnd
myGui.Opt("+AlwaysOnTop -Caption +Owner +LastFound"), var1 := myGui.Hwnd, var2 := myGui.Hwnd