; V1toV2: Removed MyVar := ComObjMissing()

ComObj(0x10) ; V1toV2: Removed ComObjMissing() variable MyVar
ComObj(, 0x10) ; V1toV2: Removed ComObjMissing() variable MyVar
ComObj() ; V1toV2: Removed ComObjMissing() variable MyVar

ComObj(0x10) ; V1toV2: Removed ComObjMissing()
ComObj(, 0x10) ; V1toV2: Removed ComObjMissing()
ComObj() ; V1toV2: Removed ComObjMissing() ; V1toV2: Removed ComObjMissing()

Var1 := "test" ; V1toV2: Removed Var2 := ComObjMissing()
 Var4 := "test" ; V1toV2: Removed Var3 := ComObjMissing()
; V1toV2: Removed Var5 := ComObjMissing(), Var6 := ComObjMissing()