VarSetCapacity(vTarget, RequestedCapacity, FillByte) * 0
VarSetCapacity(vTarget, RequestedCapacity, FillByte) * 1
VarSetCapacity(vTarget, RequestedCapacity, FillByte) + 1
VarSetCapacity(vTarget, RequestedCapacity, FillByte) - 0.1
VarSetCapacity(vTarget, RequestedCapacity, FillByte) / 1
VarSetCapacity(vTarget, RequestedCapacity, FillByte) // 4
VarSetCapacity(vTarget, RequestedCapacity, FillByte)*.5
VarSetCapacity(vTarget, RequestedCapacity, FillByte)+0
VarSetCapacity(vTarget, RequestedCapacity, FillByte)-0.1
