Transform, _Mod, Mod, 123, 100
Transform, _Exp, Exp, 2
Transform, _Sqrt, Sqrt, 2
Transform, _Log, Log, 100
Transform, _Ln, Ln, 100
Transform, _Round, Round, 3.14159, 2
Transform, _Ceil, Ceil, 3.14159
Transform, _Floor, Floor, 3.14159
Transform, _Abs, Abs, -99
Transform, _Sin, Sin, 90
Transform, _Cos, Cos, 180
Transform, _Tan, Tan, 270
Transform, _ASin, ASin, 1
Transform, _ACos, ACos, 1
Transform, _ATan, ATan, 1
Transform, _Pow, Pow, 2, 2

MsgBox, %_Mod%`n%_Exp%`n%_Sqrt%`n%_Log%`n%_Ln%`n%_Round%`n%_Ceil%`n%_Floor%`n%_Abs%`n%_Sin%`n%_Cos%`n%_Tan%`n%_ASin%`n%_ACos%`n%_ATan%`n%_Pow%